src/main/java/cn/org/hentai/simulator/web/entity/Route.java
package cn.org.hentai.simulator.web.entity;

import java.io.Serializable;

public class Route implements Serializable {
    /**
     *   id
     *
     */
    private Long id;

    /**
     *   when
     *
     */
    private String name;

    /**
     *   minSpeed（公里每小时）
     *
     */
    private Integer minSpeed;

    /**
     *   maxSpeed
     *
     */
    private Integer maxSpeed;

    /**
     *   里程（公里）
     *
     */
    private Integer mileages;

    private String fingerPrint;

    /**
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method returns the value of the database column x_route.id
     *
     * @return the value of x_route.id
     */
    public Long getId() {
        return id;
    }

    /**
     */
    public Route withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method sets the value of the database column x_route.id
     *
     * @param id the value for x_route.id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method returns the value of the database column x_route.when
     *
     * @return the value of x_route.when
     */
    public String getName() {
        return name;
    }

    /**
     */
    public Route withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method sets the value of the database column x_route.when
     *
     * @param name the value for x_route.when
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method returns the value of the database column x_route.minSpeed
     *
     * @return the value of x_route.minSpeed
     */
    public Integer getMinSpeed() {
        return minSpeed;
    }

    /**
     */
    public Route withMinSpeed(Integer minSpeed) {
        this.setMinSpeed(minSpeed);
        return this;
    }

    /**
     * This method sets the value of the database column x_route.minSpeed
     *
     * @param minSpeed the value for x_route.minSpeed
     */
    public void setMinSpeed(Integer minSpeed) {
        this.minSpeed = minSpeed;
    }

    /**
     * This method returns the value of the database column x_route.maxSpeed
     *
     * @return the value of x_route.maxSpeed
     */
    public Integer getMaxSpeed() {
        return maxSpeed;
    }

    /**
     */
    public Route withMaxSpeed(Integer maxSpeed) {
        this.setMaxSpeed(maxSpeed);
        return this;
    }

    /**
     * This method sets the value of the database column x_route.maxSpeed
     *
     * @param maxSpeed the value for x_route.maxSpeed
     */
    public void setMaxSpeed(Integer maxSpeed) {
        this.maxSpeed = maxSpeed;
    }

    /**
     * This method returns the value of the database column x_route.mileages
     *
     * @return the value of x_route.mileages
     */
    public Integer getMileages() {
        return mileages;
    }

    /**
     */
    public Route withMileages(Integer mileages) {
        this.setMileages(mileages);
        return this;
    }

    public Integer getKilometers()
    {
        if (this.mileages == null) return null;
        else return this.mileages / 1000;
    }

    /**
     * This method sets the value of the database column x_route.mileages
     *
     * @param mileages the value for x_route.mileages
     */
    public void setMileages(Integer mileages) {
        this.mileages = mileages;
    }

    public String getFingerPrint()
    {
        return fingerPrint;
    }

    public Route setFingerPrint(String fingerPrint)
    {
        this.fingerPrint = fingerPrint;
        return this;
    }

    /**
     */
    @Override
    public String toString()
    {
        return "Route{" + "id=" + id + ", when='" + name + '\'' + ", minSpeed=" + minSpeed + ", maxSpeed=" + maxSpeed + ", mileages=" + mileages + ", fingerPrint='" + fingerPrint + '\'' + '}';
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Route route = (Route) o;

        if (getId() != null ? !getId().equals(route.getId()) : route.getId() != null) return false;
        if (getName() != null ? !getName().equals(route.getName()) : route.getName() != null) return false;
        if (getMinSpeed() != null ? !getMinSpeed().equals(route.getMinSpeed()) : route.getMinSpeed() != null)
            return false;
        if (getMaxSpeed() != null ? !getMaxSpeed().equals(route.getMaxSpeed()) : route.getMaxSpeed() != null)
            return false;
        if (getMileages() != null ? !getMileages().equals(route.getMileages()) : route.getMileages() != null)
            return false;
        if (getFingerPrint() != null ? !getFingerPrint().equals(route.getFingerPrint()) : route.getFingerPrint() != null)
            return false;

        return true;
    }

    @Override
    public int hashCode()
    {
        int result = getId() != null ? getId().hashCode() : 0;
        result = 31 * result + (getName() != null ? getName().hashCode() : 0);
        result = 31 * result + (getMinSpeed() != null ? getMinSpeed().hashCode() : 0);
        result = 31 * result + (getMaxSpeed() != null ? getMaxSpeed().hashCode() : 0);
        result = 31 * result + (getMileages() != null ? getMileages().hashCode() : 0);
        result = 31 * result + (getFingerPrint() != null ? getFingerPrint().hashCode() : 0);
        return result;
    }

    /**
     */
    public enum Column {
        id("id"),
        name("when"),
        minSpeed("minSpeed"),
        maxSpeed("maxSpeed"),
        mileages("mileages"),
        fingerPrint("fingerPrint");

        /**
         */
        private final String column;

        /**
         */
        public String value() {
            return this.column;
        }

        /**
         */
        public String getValue() {
            return this.column;
        }

        /**
         */
        Column(String column) {
            this.column = column;
        }

        /**
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}

src/main/java/cn/org/hentai/simulator/web/controller/MonitorController.java
package cn.org.hentai.simulator.web.controller;

import cn.org.hentai.simulator.entity.TaskInfo;
import cn.org.hentai.simulator.manager.RouteManager;
import cn.org.hentai.simulator.task.TaskManager;
import cn.org.hentai.simulator.web.entity.Route;
import cn.org.hentai.simulator.web.service.RouteService;
import cn.org.hentai.simulator.web.vo.Page;
import cn.org.hentai.simulator.web.vo.Result;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping("/monitor/list")
public class MonitorController extends BaseController
{
    @Autowired
    RouteService routeService;

    @RequestMapping("/index")
    public String index()
    {
        return "monitor-list-index";
    }

    @RequestMapping("/json")
    @ResponseBody
    public Result listJson(@RequestParam(defaultValue = "1") int pageIndex, @RequestParam(defaultValue = "20") int pageSize)
    {
        Result result = new Result();
        try
        {
            Page<TaskInfo> page = TaskManager.getInstance().find(pageIndex, pageSize);
            for (TaskInfo task : page.getList())
            {
                Route route = routeService.getById(task.getRouteId());
                if (route != null)
                {
                    task.setRouteName(route.getName());
                    task.setRouteMileages(route.getMileages());
                }
            }
            result.setData(page);
        }
        catch(Exception ex)
        {
            result.setError(ex);
        }
        return result;
    }
}

src/main/java/cn/org/hentai/simulator/web/controller/RouteController.java
package cn.org.hentai.simulator.web.controller;

import cn.org.hentai.simulator.entity.DrivePlan;
import cn.org.hentai.simulator.manager.RouteManager;
import cn.org.hentai.simulator.util.MD5;
import cn.org.hentai.simulator.web.entity.Route;
import cn.org.hentai.simulator.web.entity.RoutePoint;
import cn.org.hentai.simulator.web.entity.StayPoint;
import cn.org.hentai.simulator.web.entity.TroubleSegment;
import cn.org.hentai.simulator.web.service.RoutePointService;
import cn.org.hentai.simulator.web.service.RouteService;
import cn.org.hentai.simulator.web.service.StayPointService;
import cn.org.hentai.simulator.web.service.TroubleSegmentService;
import cn.org.hentai.simulator.web.vo.Page;
import cn.org.hentai.simulator.web.vo.Result;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Date;
import java.util.List;

/**
 * Created by houcheng when 2018/11/25.
 * 线路控制器
 */
@Controller
@RequestMapping("/route")
public class RouteController
{
    @Autowired
    RouteService routeService;

    @Autowired
    private RoutePointService routePointService;

    @Autowired
    private StayPointService stayPointService;

    @Autowired
    private TroubleSegmentService troubleSegmentService;

    @Value("${map.baidu.key}")
    String baiduMapKey;

    @RequestMapping("/index")
    public String index()
    {
        return "routes";
    }

    @RequestMapping("/list")
    @ResponseBody
    public Result list(@RequestParam(defaultValue = "1") int pageIndex, @RequestParam(defaultValue = "20") int pageSize)
    {
        Result result = new Result();
        try
        {
            Page<Route> routes = routeService.find(null, pageIndex, pageSize);

            result.setData(routes);
        } catch (Exception ex)
        {
            result.setError(ex);
        }
        return result;
    }

    /**
     * 创建线路并跳转到编辑页面
     *
     * @return
     */
    @RequestMapping("/create")
    public String create(Model model)
    {
        model.addAttribute("baiduMapKey", baiduMapKey);
        return "route-create";
    }

    /**
     * 保存线路信息、 轨迹点、停留点、问题路段
     *
     * @param name
     * @param minSpeed
     * @param maxSpeed
     * @param mileages
     * @param pointsJsonText
     * @param stayPointsJsonText
     * @param segmentsJsonText
     * @return
     */
    @RequestMapping("/save")
    @ResponseBody
    public Result save(@RequestParam String name,
                       @RequestParam Integer minSpeed,
                       @RequestParam Integer maxSpeed,
                       @RequestParam Integer mileages,
                       @RequestParam String pointsJsonText,
                       @RequestParam String stayPointsJsonText,
                       @RequestParam String segmentsJsonText)
    {
        Result result = new Result();
        try
        {
            // 根据线路ID获取信息
            Route route = new Route();
            route.setName(name);
            route.setMinSpeed(minSpeed);
            route.setMaxSpeed(maxSpeed);
            route.setMileages(mileages);

            StringBuilder signature = new StringBuilder(4096 * 10);
            signature.append(String.valueOf(minSpeed));
            signature.append(String.valueOf(maxSpeed));
            signature.append(String.valueOf(mileages));
            signature.append(pointsJsonText);
            signature.append(stayPointsJsonText);
            signature.append(segmentsJsonText);
            String fingerPrint = MD5.encode(signature.toString());
            route.setFingerPrint(fingerPrint);

            routeService.create(route);

            long id = route.getId();

            // 添加原轨迹点
            List<RoutePoint> points = null;
            if (!StringUtils.isEmpty(pointsJsonText))
            {
                points = new Gson().fromJson(pointsJsonText, new TypeToken<List<RoutePoint>>()
                {
                }.getType());
            }
            if (points != null)
            {
                for (RoutePoint point : points)
                {
                    point.setLatitude(point.getLat());
                    point.setLongitude(point.getLng());
                    point.setRouteId(id);
                }
                routePointService.batchSave(route, points);
            }

            // 添加停留点
            List<StayPoint> stayPoints = null;
            if (!StringUtils.isEmpty(stayPointsJsonText))
            {
                stayPoints = new Gson().fromJson(stayPointsJsonText, new TypeToken<List<StayPoint>>()
                {
                }.getType());
            }
            if (stayPoints != null)
            {
                for (StayPoint stayPoint : stayPoints)
                {
                    stayPoint.setId(null);
                    stayPoint.setRouteid(id);
                }
                this.stayPointService.save(route, stayPoints);
            }

            // 添加问题路段
            List<TroubleSegment> troubleSegments = null;
            if (!StringUtils.isEmpty(segmentsJsonText))
            {
                troubleSegments = new Gson().fromJson(segmentsJsonText, new TypeToken<List<TroubleSegment>>()
                {
                }.getType());
            }
            if (troubleSegments != null)
            {
                for (TroubleSegment segment : troubleSegments)
                {
                    segment.setId(null);
                    segment.setRouteId(id);
                }
                this.troubleSegmentService.save(route, troubleSegments);
            }

            // 更新内存中的线路缓存
            RouteManager.getInstance().load(route);
        } catch (Exception e)
        {
            result.setError(e);
        }
        return result;
    }
}

src/main/resources/templates/monitor-list-index.ftl
<!DOCTYPE html>
<html lang="en">
<head>
<#include "inc/resource.ftl">
    <title>行程任务</title>
</head>
<body>
<div class="container">
<#include "inc/sidebar.ftl">
    <div class="content datasheet">
        <h2>行程任务</h2>
        <hr />
        <div id="route-table"></div>
        <ul class="pagination"></ul>
    </div>
</div>
</body>
<#include "inc/footer.ftl">
<script type="text/javascript">
    $(document).ready(function()
    {
        setCurrentMenu('list-monitor');
        $('#route-table').paginate({
            url: '${context}/monitor/list/json',
            fields: [
                {
                    name: 'routeName',
                    title: '线路名称',
                    align: 'left',
                },
                {
                    name : 'routeMileages',
                    title : '线路里程',
                    align : 'right',
                    formatter : function(i, v, r)
                    {
                        return parseInt(v / 1000) + ' km';
                    }
                },
                {
                    name: 'vehicleNumber',
                    title: '车牌号',
                    align: 'center',
                },
                {
                    name: 'simNumber',
                    title: 'SIM卡号',
                    align: 'center',
                },
                {
                    name: 'deviceSn',
                    title: '终端ID',
                    align: 'center',
                },
                {
                    name : 'startTime',
                    title : '启动时间',
                    align : 'center',
                    formatter : function(i, v, r)
                    {
                        return new Date(v).format('yyyy-MM-dd hh:mm:ss');
                    }
                },
                {
                    name : 'longitude',
                    title : '经度',
                    align : 'right',
                    formatter : function(i, v, r)
                    {
                        return v ? String(v).replace(/^(\d+\.\d{6})\d+$/gi, '$1') : '--';
                    }
                },
                {
                    name : 'latitude',
                    title : '纬度',
                    align : 'right',
                    formatter : function(i, v, r)
                    {
                        return v ? String(v).replace(/^(\d+\.\d{6})\d+$/gi, '$1') : '--';
                    }
                },
                {
                    name: 'id',
                    title: '操作',
                    align: 'center',
                    width : '160px',
                    formatter: function (i, v, r)
                    {
                        var html = '';
                        html += '<a href="${context}/monitor/view?id=' + v + '" target="_blank" class="btn btn-sm btn-blue">详情</a>';
                        return html;
                    }
                }
            ]
        });
    });
</script>
</html>

src/main/resources/templates/routes.ftl
<!DOCTYPE html>
<html lang="en">
<head>
<#include "inc/resource.ftl">
    <title>线路管理</title>
</head>
<body>
<div class="container">
<#include "inc/sidebar.ftl">
    <div class="content datasheet">
        <h2>线路管理<a href="${context}/route/create" class="btn btn-sm btn-blue pull-right">创建新线路</a></h2>
        <hr />
        <div id="route-table"></div>
        <ul class="pagination"></ul>
    </div>
</div>
</body>
<#include "inc/footer.ftl">
<script type="text/javascript">
    $(document).ready(function()
    {
        setCurrentMenu('route');
        $('#route-table').paginate({
            url: '${context}/route/list',
            fields: [
                {
                    name: 'id',
                    title: '线路ID',
                    align: 'center',
                    width: '160px',
                    formatter: function (i, v, r)
                    {
                        return v;
                    }
                },
                {
                    name: 'name',
                    title: '线路名称',
                    align: 'left',
                    formatter: function (i, v, r)
                    {

                        return v;
                    }
                },
                {
                    name: 'minSpeed',
                    title: '最低速度',
                    align: 'right',
                    width : '160px',
                    formatter: function (i, v, r)
                    {
                        return v + ' km/h';
                    }
                },
                {
                    name: 'maxSpeed',
                    title: '最高速度',
                    align: 'right',
                    width : '160px',
                    formatter: function (i, v, r)
                    {
                        return v + ' km/h';
                    }
                },
                {
                    name: 'mileages',
                    title: '里程',
                    align: 'right',
                    width : '160px',
                    formatter: function (i, v, r)
                    {
                        return v ? (v / 1000).toFixed(1) + ' km' : '--';
                    }
                },
                {
                    name: '-',
                    title: '操作',
                    align: 'center',
                    width : '160px',
                    formatter: function (i, v, r)
                    {
                        var html = '';
                        html += '<a href="${context}/route/edit?id=' + r.id + '" target="_blank" class="btn btn-sm btn-blue">编辑</a>';
                        return html;
                    }
                }
            ]
        });
    });
</script>
</html>

src/main/resources/templates/sample.ftl
<!DOCTYPE html>
<html lang="en">
<head>
    <#include "inc/resource.ftl">
    <title>网页标题</title>
</head>
<body>
<div class="container">
    <#include "inc/sidebar.ftl">
    <div class="content">
        内容区
    </div>
</div>
</body>
<#include "inc/footer.ftl">
</html>

src/main/resources/templates/task-batch-create.ftl
<!DOCTYPE html>
<html lang="en">
<head>
    <#include "inc/resource.ftl">
    <title>批量创建行程</title>
    <style type="text/css">
        .container .content .x-row
        {
            xheight: 40px;
            line-height: 40px;
        }
        .container .content
        {
            padding: 20px 20px 20px 20px;
        }
        .content .x-col-2 input { width: 100%; }
        .x-hint
        {
            color: #999999;
            padding: 0px 10px 0px 10px;
        }
    </style>
</head>
<body>
<div class="container">
    <#include "inc/sidebar.ftl">
    <div class="content">
        <h2>批量创建行程任务</h2>
        <hr />
        <div class="x-row">
            <div class="x-col-2 text-right">行驶线路：</div>
            <div class="x-col-6">
                <select name="routeId" id="routeId" multiple size="20" style="height: 300px;">
                    <option value="0" selected>- 随机分配 -</option>
                    <#list routes as item>
                        <option value="${item.id}">${item.name} - ${item.kilometers!'NaN'}公里</option>
                    </#list>
                </select>
            </div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">车辆数量：</div>
            <div class="x-col-2"><input type="text" name="vehicleCount" id="vehicleCount" placeholder="最高不超过100000" value="1000" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">车牌号：</div>
            <div class="x-col-2"><input type="text" name="vehicleNumberPattern" id="vehicleNumberPattern" placeholder="如：京%06d" value="京%06d" /></div>
            <div class="x-col-4"><span class="x-hint">如<strong>%06d</strong>表示六个数字，左侧补0，从0~车辆数量的序号生成车牌号</span></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">终端ID：</div>
            <div class="x-col-2"><input type="text" name="deviceSnPattern" id="deviceSnPattern" placeholder="如：A%06d" value="A%06d" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">终端SIM卡号：</div>
            <div class="x-col-2"><input type="text" name="simNumberPatter" id="simNumberPattern" placeholder="如：013800%06d，12位数字" value="013800%06d" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">808网关服务器：</div>
            <div class="x-col-2"><input type="text" name="serverAddress" id="serverAddress" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">808网关服务器端口：</div>
            <div class="x-col-2"><input type="text" name="serverPort" id="serverPort" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">&nbsp;</div>
            <div class="x-col-4">
                <button class="btn btn-blue" id="btn-run">创建</button>
            </div>
            <div class="x-clearfix"></div>
        </div>
    </div>
</div>
</body>
<#include "inc/footer.ftl">
<script type="text/javascript">
    $(document).ready(function()
    {
        setCurrentMenu('batch');

        $('#btn-run').click(function()
        {
            var idList = [];
            $('#routeId option:selected').each(function()
            {
                idList.push(this.value);
            });

            var params = {
                routeIdList : idList,
                vehicleCount : $('#vehicleCount').val(),
                vehicleNumberPattern : $('#vehicleNumberPattern').val(),
                deviceSnPattern : $('#deviceSnPattern').val(),
                simNumberPattern : $('#simNumberPattern').val(),
                serverAddress : $('#serverAddress').val(),
                serverPort : $('#serverPort').val()
            };
            $.post('./run', params, function(result)
            {
                if (result.error && result.error.code) return toastr('error', result.error.reason);
                else toastr('success', '启动成功');
            });
        });
    });
</script>
</html>

src/main/resources/templates/task-create.ftl
<!DOCTYPE html>
<html lang="en">
<head>
    <#include "inc/resource.ftl">
    <title>创建临时行程</title>
    <style type="text/css">
        .container .content .x-row
        {
            height: 40px;
            line-height: 40px;
        }
        .container .content
        {
            padding: 20px 20px 20px 20px;
        }
    </style>
</head>
<body>
<div class="container">
    <#include "inc/sidebar.ftl">
    <div class="content">
        <h2>创建临时行程任务</h2>
        <hr />
        <div class="x-row">
            <div class="x-col-2 text-right">行驶线路：</div>
            <div class="x-col-6">
                <select name="routeId" id="routeId" class="">
                    <option value="0">- 请选择行驶线路 -</option>
                    <#list routes as item>
                        <option value="${item.id}">${item.name} - ${item.kilometers!'NaN'}公里</option>
                    </#list>
                </select>
            </div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">车牌号：</div>
            <div class="x-col-6"><input type="text" name="vehicleNumber" id="vehicleNumber" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">终端ID：</div>
            <div class="x-col-6"><input type="text" name="deviceSn" id="deviceSn" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">终端SIM卡号：</div>
            <div class="x-col-6"><input type="text" name="simNumber" id="simNumber" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">808网关服务器：</div>
            <div class="x-col-6"><input type="text" name="serverAddress" id="serverAddress" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">808网关服务器端口：</div>
            <div class="x-col-6"><input type="text" name="serverPort" id="serverPort" /></div>
            <div class="x-clearfix"></div>
        </div>
        <div class="x-row">
            <div class="x-col-2 text-right">&nbsp;</div>
            <div class="x-col-6">
                <button class="btn btn-blue" id="btn-run">启动</button>
            </div>
            <div class="x-clearfix"></div>
        </div>
    </div>
</div>
</body>
<#include "inc/footer.ftl">
<script type="text/javascript">
    $(document).ready(function()
    {
        setCurrentMenu("task");
        $('#btn-run').click(function()
        {
            var params = {
                routeId : $('#routeId').val(),
                vehicleNumber : $('#vehicleNumber').val(),
                deviceSn : $('#deviceSn').val(),
                simNumber : $('#simNumber').val(),
                serverAddress : $('#serverAddress').val(),
                serverPort : $('#serverPort').val()
            };

            $.post('./run', params, function(result)
            {
                if (result.error && result.error.code) return toastr('error', result.error.reason);
                else
                {
                    toastr('success', '启动成功');
                }
            });
        });
    });
</script>
</html>